version: '3.8'
services:
  grpc:
    image: ghcr.io/riccardobl/openagents-grpc:master
    networks:
      - openagents-node-network

  extism-runtime:
    image: ghcr.io/riccardobl/openagents-extism-runtime-node:master
    environment:
      - NOSTR_CONNECT_GRPC_BINDING_ADDRESS=grpc
      - NOSTR_CONNECT_GRPC_BINDING_PORT=5000
    networks:
      - openagents-node-network

networks:
  openagents-node-network:
    driver: bridge